export const Menus = {
    '/indent-management': 'home/module/indent',
    '/module/indent/active': 'home/module/indent',
    '/module/indent/old': 'home/module/indent',
    '/module/indent/create': 'home/module/indent',
    '/indent-management/aged-challans': 'home/module/indent',
    '/indent-management/cancelled-idc': 'home/module/indent',
    '/indent-management/challan-status': 'home/module/indent',
    '/indent-management/distillery-indent': 'home/module/indent',
    '/indent-management/reconciled-challanas': 'home/module/indent',
    '/indent-management/retailer-cards': 'home/module/indent',
    '/indent-management/special-indent': 'home/module/indent',
    '/indent-management/upload-cards': 'home/module/indent',
    '/indent-management/special-ifs': 'home/module/indent',
    '/user': 'home/user',
    '/user/apbcl': 'home/user',
    '/user/depot': 'home/user',
    '/user/retailers': 'home/user',
    '/distillery': 'home/distillery',
    '/distillery/products': 'home/distillery',
    '/distillery/stock': 'home/distillery',
    '/distillery/beer-stock': 'home/distillery',
    '/distillery/ofs': 'home/distillery',
    '/distillery/route': 'home/distillery',
    '/depots': 'home/depots',
    '/depots/depots-stock': 'home/depots',
    '/depots/depots-breakage-verification': 'home/depots',
    '/depots/depots-challan': 'home/depots',
    '/depots/depots-retailer-returns': 'home/depots',
    '/licensee-profiles': 'home/licensee-profiles',
    '/licensee-profiles/bars': 'home/licensee-profiles',
    '/licensee-profiles/clubs': 'home/licensee-profiles',
    '/licensee-profiles/elite': 'home/licensee-profiles',
    '/licensee-profiles/ep1': 'home/licensee-profiles',
    '/licensee-profiles/expired-licensee': 'home/licensee-profiles',
    '/licensee-profiles/f2': 'home/licensee-profiles',
    '/licensee-profiles/licensee-status': 'home/licensee-profiles',
    '/licensee-profiles/suspended-retailers': 'home/licensee-profiles',
    '/licensee-profiles/t2': 'home/licensee-profiles',
    '/licensee-profiles/shops': 'home/licensee-profiles',
    '/licensee-profiles/td1-td2': 'home/licensee-profiles',
    '/bcl-outlets': 'home/bcl-outlets',
    '/bcl-outlets/outlet-profiles': 'home/bcl-outlets',
    '/bcl-outlets/outlet-returns': 'home/bcl-outlets',
    '/bcl-outlets/outlet-sales': 'home/bcl-outlets',
    '/bcl-outlets/outlet-status': 'home/bcl-outlets',
    '/licensee-sales': 'home/licensee-sales',
    '/licensee-sales/bar-sales': 'home/licensee-sales',
    '/licensee-sales/club-sales': 'home/licensee-sales',
    '/licensee-sales/shop-sales': 'home/licensee-sales',
    '/licensee-sales/td1-sales': 'home/licensee-sales',
    '/licensee-sales/td2-sales': 'home/licensee-sales',
    '/hologram': 'home/hologram',
    '/hologram/indent-daily': 'home/hologram',
    '/hologram/indent-purchase': 'home/hologram',
    '/hologram/distillery': 'home/hologram',
    '/hologram/depot': 'home/hologram',
    '/lab': 'home/lab',
    '/lab/samples': 'home/lab',
    '/lab/finished': 'home/lab',
    '/lab/reports': 'home/lab',
    '/lab/batch-deactivation': 'home/lab',
    '/shipment': 'home/shipment',
    '/shipment/shipment-ofs': 'home/shipment',
    '/shipment/shipment-shipments': 'home/shipment',
    '/shipment/shipment-router': 'home/shipment',
    '/shipment/shipment-distillery': 'home/shipment',
    '/shipment/shipment-revalidation': 'home/shipment',
    '/shipment/shipment-depot': 'home/shipment',
    '/imports': 'home/import',
    '/import': 'home/import',
    '/import-shipment': 'home/import',
    '/production': 'home/production',
    '/production/products': 'home/production',
    '/production/production-line': 'home/production',
    '/production/production-start': 'home/production',
    '/production/production-report': 'home/production',
    '/production/manual-production': 'home/production',
    '/inter-depot': 'home/inter-depot',
    '/depot-home/depot-transfer': 'home/inter-depot',
    '/depot-home/depot-local': 'home/inter-depot',
    '/depot-home/depot-transfer-supplier': 'home/inter-depot',
    '/depot-home/depot-local-supplier': 'home/inter-depot',
    '/breakages': 'home/breakages',
    '/breakages/breakages-depot': 'home/breakages',
    '/breakages/shortage': 'home/breakages',
    '/products': 'home/products',
    '/products/products-brand': 'home/products',
    '/products/products-products': 'home/products',
    '/products/products-iteamcode': 'home/products',
    '/beer': 'home/beer',
    '/beer/beer-ofs-entitlement': 'home/beer',
    '/beer/beer-shipment': 'home/beer',
    '/beer/beer-indent': 'home/beer',
    '/beer/beer-indent-special': 'home/beer',
    '/pricing/basic-price-rules': 'home/pricing',
    '/pricing': 'home/pricing',
    '/pricing/coomputed-prices': 'home/pricing',
    '/pricing/mrp-performance': 'home/pricing',
    '/pricing/offered-basic-price': 'home/pricing',
    '/pricing/ofs-approval': 'home/pricing',
    '/pricing/recompute': 'home/pricing',
    '/pricing/recompute-brandwise': 'home/pricing',
    '/pricing/state-levy': 'home/pricing',
    '/module/transactions': 'home/module/transactions',
    '/module/supplier-payment': 'home/module/transactions',
    '/module/transaction': 'home/module/transactions',
    '/module/transaction-rollback': 'home/module/transactions',
    '/module/grn-processingfee': 'home/module/transactions',
    '/module/penality-report': 'home/module/transactions',
    '/module/missupplier-payment': 'home/module/transactions',
    '/module/gnrsupplier-payment': 'home/module/transactions',
    '/module/consolidate-payment': 'home/module/transactions',
    '/module/penality-details': 'home/module/transactions',
    '/module/supplierwise': 'home/module/transactions',
    '/module/processfee': 'home/module/transactions',
    '/module/stock': 'home/module/stock',
    '/spirit': 'home/spirit',
    '/spirit/procurement': 'home/spirit',
    '/spirit/print-approved': 'home/spirit',
    '/spirit/receipit': 'home/spirit',
    '/excise': 'home/excise',
    '/excise-duty/duties': 'home/excise',
    '/excise-duty/remitance': 'home/excise',
    '/excise-duty/department': 'home/excise',
    '/Wallet': 'home/Wallet',
    '/cart': 'home/cart',
    '/module/alerts': 'home/module/alerts',
    '/module/alerts/subscription': 'home/module/alerts',
    '/module/alerts/circulars': 'home/module/alerts',
    '/module/alerts/alert': 'home/module/alerts',
    '/module/feedback': 'home/module/feedback',
    '/module/feedback/feedback-feedback': 'home/module/feedback',
    '/module/feedback/feedback-issue': 'home/module/feedback',
    '/vehicle-tracking': 'home/vehicle-tracking',
    '/update-stock': 'home/vehicle-tracking',
    '/add-vehicle-tracking': 'home/vehicle-tracking',
    '/vehicle-tracking-route': 'home/vehicle-tracking',
    '/add-route': 'home/vehicle-tracking'
};

export const SubMenus = [
    '/module/indent/active',
    '/module/indent/old',
    '/module/indent/create',
    '/indent-management/aged-challans',
    '/indent-management/cancelled-idc',
    '/indent-management/challan-status',
    '/indent-management/distillery-indent',
    '/indent-management/reconciled-challanas',
    '/indent-management/retailer-cards',
    '/indent-management/special-indent',
    '/indent-management/upload-cards',
    '/indent-management/special-ifs',
    '/user/apbcl',
    '/user/depot',
    '/user/retailers',
    '/distillery/products',
    '/distillery/stock',
    '/distillery/beer-stock',
    '/distillery/ofs',
    '/distillery/route',
    '/depots/depots-stock',
    '/depots/depots-breakage-verification',
    '/depots/depots-challan',
    '/depots/depots-retailer-returns',
    '/licensee-profiles/bars',
    '/licensee-profiles/clubs',
    '/licensee-profiles/elite',
    '/licensee-profiles/ep1',
    '/licensee-profiles/expired-licensee',
    '/licensee-profiles/f2',
    '/licensee-profiles/licensee-status',
    '/licensee-profiles/suspended-retailers',
    '/licensee-profiles/t2',
    '/licensee-profiles/shops',
    '/licensee-profiles/td1-td2',
    '/bcl-outlets/outlet-profiles',
    '/bcl-outlets/outlet-returns',
    '/bcl-outlets/outlet-sales',
    '/bcl-outlets/outlet-status',
    '/licensee-sales/bar-sales',
    '/licensee-sales/club-sales',
    '/licensee-sales/shop-sales',
    '/licensee-sales/td1-sales',
    '/licensee-sales/td2-sales',
    '/hologram/indent-daily',
    '/hologram/indent-purchase',
    '/hologram/distillery',
    '/hologram/depot',
    '/lab/samples',
    '/lab/finished',
    '/lab/reports',
    '/lab/batch-deactivation',
    '/shipment/shipment-ofs',
    '/shipment/shipment-shipments',
    '/shipment/shipment-router',
    '/shipment/shipment-distillery',
    '/shipment/shipment-revalidation',
    '/shipment/shipment-depot',
    '/import',
    '/import-shipment',
    '/production/products',
    '/production/production-line',
    '/production/production-start',
    '/production/production-report',
    '/production/manual-production',
    '/depot-home/depot-transfer',
    '/depot-home/depot-local',
    '/depot-home/depot-transfer-supplier',
    '/depot-home/depot-local-supplier',
    '/breakages/breakages-depot',
    '/breakages/shortage',
    '/products/products-brand',
    '/products/products-products',
    '/products/products-iteamcode',
    '/beer/beer-ofs-entitlement',
    '/beer/beer-shipment',
    '/beer/beer-indent',
    '/beer/beer-indent-special',
    '/pricing/basic-price-rules',
    '/pricing/coomputed-prices',
    '/pricing/mrp-performance',
    '/pricing/offered-basic-price',
    '/pricing/ofs-approval',
    '/pricing/recompute',
    '/pricing/recompute-brandwise',
    '/pricing/state-levy',
    '/module/supplier-payment',
    '/module/transaction',
    '/module/transaction-rollback',
    '/module/grn-processingfee',
    '/module/penality-report',
    '/module/missupplier-payment',
    '/module/gnrsupplier-payment',
    '/module/consolidate-payment',
    '/module/penality-details',
    '/module/supplierwise',
    '/module/processfee',
    '/spirit/procurement',
    '/spirit/print-approved',
    '/spirit/receipit',
    '/excise-duty/duties',
    '/excise-duty/remitance',
    '/excise-duty/department',
    '/Wallet',
    '/module/alerts/subscription',
    '/module/alerts/circulars',
    '/module/alerts/alert',
    '/module/feedback/feedback-feedback',
    '/module/feedback/feedback-issue',
    '/update-stock',
    '/add-vehicle-tracking',
    '/vehicle-tracking-route',
    '/add-route'
];
